name: ci

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.14.0
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    with:
      number-of-agents: 3
      parallel-commands: |
        npx nx-cloud record -- yarn nx format:check
      parallel-commands-on-agents: |
        yarn nx affected -t lint --parallel=3 & yarn nx affected -t test --parallel=3 --configuration=ci & yarn nx affected -t build --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.14.0
    with:
      number-of-agents: 3
