name: ci

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: ./.github/workflows/nx-cloud-main.yml
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    with:
      number-of-agents: 3
      init-commands: |
        yarn exec nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      parallel-commands: |
        yarn exec nx-cloud record -- yarn exec nx workspace-lint
      parallel-commands-on-agents: |
        yarn exec nx affected --target=lint --parallel=3
        yarn exec nx affected --target=test --parallel=3 --ci --code-coverage
        yarn exec nx affected --target=build --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: ./.github/workflows/nx-cloud-agents.yml
    with:
      number-of-agents: 3
